// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EntityOperations
{
    public partial class NewAccountTable
    {
        public int Id { get; set; }
        public string CustomerAccountNumber { get; set; }
    }
}